# Generated by Django 4.0.6 on 2022-09-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('imgs', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('body', models.TextField()),
                ('avtor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('years', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('category', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aziret.category')),
            ],
        ),
    ]
